### ISSUE TITLE
"MP" in application diagram

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-reactive-service-testing#45]
The first diagram that shows the application has a "MP" in it.  We never define it in the guide.  Spell it out as "MicroProfile".  Or, "Reactive services using MicroProfile Reactive Messaging".

FYI, @gkwan-ibm.

**Comment by yeekangc** [comment]
"Restful" should be "RESTful" too.

**Comment by ankitagrawa** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/8294670/80834078-04468900-8bbe-11ea-87f7-6f964ca0f777.png">

@yeekangc  : Is this good?
@gkwan-ibm @MaiHameed : FYI

**Comment by yeekangc** [comment]
Thanks.
