### ISSUE TITLE
Initial `mvn verify` fails if you have an older image cached in local Docker registry

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/guide-reactive-service-testing#55]
The initial instructions:

1. mvn -pl models install
2. cd system; mvn verify

fail if you have an older version of image:tag:   **openliberty/open-liberty:kernel-java8-openj9-ubi**

since the mpConfig-1.4 feature is only in the latest 20.0.0.4 fix pack.

Maybe we should tell you to do:
`docker pull openliberty/open-liberty:kernel-java8-openj9-ubi`    first?

**Comment by MaiHameed** [comment]
Good point thanks! Fixed in the linked PR.
